name: Metrics

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches: [preview]
    paths: ['.github/workflows/metrics.yml']

permissions:
  contents: write

jobs:
  metrics:
    name: Generate metrics panels
    runs-on: ubuntu-latest
    steps:
      - name: Isometric contribution calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: O-2wice
          filename: metrics/isocalendar.svg
          base: ""
          config_timezone: Europe/Budapest
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
